spring:
  application:
    name: ms-yanki
  data:
    mongodb:
      uri: mongodb://localhost:27017/yunki
  kafka:
      producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: com.ms_yanki.config.PaymentRequestSerializer
  

server:
  port: 8084